<a href="https://colab.research.google.com/github/Danielkr0l/datascience/blob/main/mno%C5%BCenie%20macierzy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([4,2,-3,1])

In [8]:

np.add(a,b)


array([5, 4, 0, 5])

In [9]:
np.multiply(a,b)

array([ 4,  4, -9,  4])

In [10]:
np.divide(a,b)

array([ 0.25,  1.  , -1.  ,  4.  ])

In [7]:
a*2

array([2, 4, 6, 8])

In [14]:
x = np.array([[1,4],[2,-5]])
y = np.array([[3,9], [6,0]])
print(x, '\n')
print(y)

[[ 1  4]
 [ 2 -5]] 

[[3 9]
 [6 0]]


In [15]:
x*y

array([[ 3, 36],
       [12,  0]])

In [16]:
np.dot(x,y)

array([[ 27,   9],
       [-24,  18]])

In [17]:
x.dot(y)

array([[ 27,   9],
       [-24,  18]])

In [18]:
x @ y

array([[ 27,   9],
       [-24,  18]])