<a href="https://colab.research.google.com/github/Danielkr0l/datascience/blob/main/random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
np.random.seed(0)

In [19]:
np.random.randn()

-1.001461808782458

In [21]:
np.random.randn(10)

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [22]:
np.random.randn(5,4)

array([[ 0.14404357,  1.45427351,  0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877]])

In [24]:
np.random.rand(10,2)

array([[0.6818203 , 0.3595079 ],
       [0.43703195, 0.6976312 ],
       [0.06022547, 0.66676672],
       [0.67063787, 0.21038256],
       [0.1289263 , 0.31542835],
       [0.36371077, 0.57019677],
       [0.43860151, 0.98837384],
       [0.10204481, 0.20887676],
       [0.16130952, 0.65310833],
       [0.2532916 , 0.46631077]])

In [29]:
np.random.randint(20)

17

In [34]:
np.random.randint(50,60, size = 5)

array([55, 50, 51, 52, 54])

In [57]:
np.random.choice([1,100,10,4,7])

100

In [59]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.random.shuffle(data)
data

array([8, 0, 4, 3, 6, 5, 1, 9, 2, 7])