<a href="https://colab.research.google.com/github/Danielkr0l/datascience/blob/main/tablice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)


1D



In [8]:
x = np.array([1, 3])
x

array([1, 3])

In [9]:
print(x)

[1 3]


In [10]:
type(x)

numpy.ndarray

In [11]:
x.ndim

1

In [12]:
x.shape

(2,)

In [13]:
x.size

2

In [14]:
x.dtype

dtype('int64')

In [15]:
y =np.array([1.4,2.5,1.6])
print(y)

[1.4 2.5 1.6]


In [17]:
y.dtype

dtype('float64')

2D


In [23]:
z = np.array([[1, 2],[-3,1]])
print(z)

[[ 1  2]
 [-3  1]]


In [22]:
z.ndim

2

In [24]:
z.shape

(2, 2)

In [25]:
t = np.array([[1,2,4], [5,2,1]])
t

array([[1, 2, 4],
       [5, 2, 1]])

In [26]:
t.shape

(2, 3)

3D

In [32]:
a = np.array(
    [[[4,3,1],
      [3,1,2]],
    
    [[5,2,3],
     [4,9,2]],
     
    [[4,6,8],
     [1,1,3]]])
print(a)

[[[4 3 1]
  [3 1 2]]

 [[5 2 3]
  [4 9 2]]

 [[4 6 8]
  [1 1 3]]]


In [33]:
a.ndim

3

In [34]:
a.shape

(3, 2, 3)

In [35]:
b = np.array(
    [[[4,3,1],
      [3,1,2]],
    
    [[5,2,3],
     [4,9,2]]])

In [36]:
b.ndim

3

In [37]:
b.shape

(2, 2, 3)