<a href="https://colab.research.google.com/github/Danielkr0l/datascience/blob/main/wycinanie%20z%20tablic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import numpy as np


In [63]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
a[10:15]

array([10, 11, 12, 13, 14])

In [70]:
a = a.reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [71]:
a[0]

array([0, 1, 2, 3, 4])

In [72]:
a[:,0]

array([ 0,  5, 10, 15])

In [73]:
a[:,-1]

array([ 4,  9, 14, 19])

In [74]:
a[1,1]

6

In [75]:
a[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])