<a href="https://colab.research.google.com/github/Danielkr0l/datascience/blob/main/numpy/dzia%C5%82ania_macierze.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
 import numpy as np

długość wektora w R^2

In [3]:
v1 = np.array([0,4])
v1

array([0, 4])

In [4]:
np.linalg.norm(v1)

4.0

Długość wektora w R^n

In [5]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

Odl 2 punktów w na płaszczyźnie

In [7]:
p = np.array([3,0])
q = np.array([0,4])

np.linalg.norm(p-q)

5.0

Odl 2 punktów w przestrzeni R^n

In [8]:
p = np.array([3,0,1])
q = np.array([0,4,2])
np.linalg.norm(p-q)

5.0990195135927845

**MNOŻENIE MACIERZY**

In [29]:
 x = np.array([[5,2],[3,9]])
 y = np.array([[1],[-1]])
 
np.dot(x,y)

x@y

array([[ 3],
       [-6]])

In [ ]:
transponowanie

Wyznacznik

In [18]:
x.T

array([[5, 3],
       [2, 9]])

Wyznacznik

In [20]:
round(np.linalg.det(x))

39

Ślad macierzy

In [21]:
np.trace(x)

14

Macierz jednostkowa

In [23]:
 np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrotna

In [25]:
a = np.array([[2,4],[-1,3]])
np.linalg.inv(a)

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

**Układy równań**

In [31]:
 A = np.array([[2,4],[1,-1]])
 B = np.array([[10], [-1]])

 inv_A = np.linalg.inv(A)

 X = inv_A @ B
 print(X)

[[1.]
 [2.]]
