<a href="https://colab.research.google.com/github/Danielkr0l/datascience/blob/main/numpy/wycinanie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np


In [6]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
a[10:15]

array([10, 11, 12, 13, 14])

In [8]:
a = a.reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
a[0]

array([0, 1, 2, 3, 4])

In [10]:
a[:,0]

array([ 0,  5, 10, 15])

In [11]:
a[:,-1]

array([ 4,  9, 14, 19])

In [12]:
a[1,1]

6

In [13]:
a[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [14]:
a[1,1] = 10
a

array([[ 0,  1,  2,  3,  4],
       [ 5, 10,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
for row in a:
  print(row[:3])

[0 1 2]
[ 5 10  7]
[10 11 12]
[15 16 17]


In [16]:
for item in a.flat:
  print(item)

0
1
2
3
4
5
10
7
8
9
10
11
12
13
14
15
16
17
18
19


In [17]:
a.shape

(4, 5)

In [18]:
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5, 10,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [19]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5, 10,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
a.T

array([[ 0,  5, 10, 15],
       [ 1, 10, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [24]:
a = np.arange(-10,10,0.5)
a = a.reshape(10,-1)
a

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [25]:
a>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [28]:
a[a> 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [29]:
np.bitwise_and(a>-5, a<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [30]:
a[np.bitwise_and(a>-5, a<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [31]:
np.bitwise_or(a<-5, a>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])